apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot-test
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatbot-test
  template:
    metadata:
      labels:
        app: chatbot-test
    spec:
      containers:
      - name: chatbot
        image: jejmb248/copyed-chatbot-image:latest  # 여기 이미지 버전 바꾸면서 테스트 가능
        ports:
        - containerPort: 5000

